Add start container task
PrefectHQ/prefect-docker pull request #18
Opened 2022-10-14 19:05 UTC by ahuang11

Closes #

### Example

### Checklist

- [ ] This pull request references any related issue by including "Closes #<ISSUE_NUMBER>"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-docker/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-docker/blob/main/CHANGELOG.md)

2022-10-15 01:28 UTC, ahuang11 commented
Converted a few PRs to drafts because I need to rebase with close_client branch and also add async.

2022-10-19 13:51 UTC, desertaxle requested changes

2022-10-19 13:51 UTC, desertaxle commented on prefect_docker/containers.py
> +        container = await run_sync_in_worker_thread(client.containers.get, container_id)
I think it'd be worthwhile to log the whole container ID once we have it.
```suggestion
        container = await run_sync_in_worker_thread(client.containers.get, container_id)
        logger.info(f"Starting container {container.id!r}")
```

2022-10-21 00:46 UTC, desertaxle approved these changes

2022-10-21 00:52 UTC, desertaxle approved these changes

2022-10-21 02:46 UTC, merged